namespace: amazon
name: amazon
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:coll-test/amazon.amazon.git
documentation: https://github.com/coll-test/amazon.amazon/tree/master/docs
homepage: https://github.com/coll-test/amazon.amazon
issues: https://github.com/coll-test/amazon.amazon/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
